#ifndef GUI_CONTROLLER_H
#define GUI_CONTROLLER_H

#include "appwindow.h"   // Generated by Slint from appwindow.slint
#include "Store.h"
#include <sstream>
#include <iomanip>

class GuiController {
private:
    Inventory            inventory;
    userManager*         um;
    std::vector<Order>   orders;
    FileManager          fm;
    User*                currentUser = nullptr;

    slint::ComponentHandle<AppWindow> ui = AppWindow::create();

    // ── Helpers ──────────────────────────────────────────────────────────────
    void updateCatalog();
    void updateCart();
    void updateOrders();

    static std::string fmtPrice(double v) {
        std::ostringstream ss;
        ss << std::fixed << std::setprecision(2) << v;
        return ss.str();
    }

public:
    GuiController();
    void run();
};

#endif